services:
  # UI Application (React + Vite served by Nginx)
  jiratickettimer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8035:80"
    depends_on:
      - api
    environment:
      - VITE_GEMINI_API_KEY=${GEMINI_API_KEY}

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: jira_tracker_db
      PORT: 5000

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: jira_tracker_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: jira_tracker_db
    ports:
      - "5422:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # PgAdmin 4 (Database Management UI)
  pgadmin:
    image: dpage/pgadmin4
    container_name: jira_tracker_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "3050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
